import React, { useState, useEffect } from 'react';
import { Settings as SettingsIcon, Building, Image, Save, FileText } from 'lucide-react';
import TelegramConfig from '../components/TelegramConfig';

export default function Settings() {
  const [settings, setSettings] = useState({
    companyName: 'TechHarmonix',
    logoUrl: 'https://www.techharmonix.com/_next/image?url=%2Fimages%2Flogo%2FLogo.png&w=256&q=75',
    primaryColor: '#1e3a8a',
    telegramBotToken: '',
    telegramChatId: '',
    enableTelegramAutoSend: true,
    reportFooterText: 'Confidential Audit Report - Generated by TechHarmonix DigiCheck Platform'
  });

  const [savedMsg, setSavedMsg] = useState(false);

  useEffect(() => {
    fetch('/api/settings')
      .then(r => r.json())
      .then(data => {
        if (data.companyName) setSettings(data);
      })
      .catch(() => {});
  }, []);

  const handleSaveBranding = async (e) => {
    if (e) e.preventDefault();
    try {
      const res = await fetch('/api/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(settings)
      });
      const data = await res.json();
      if (data.success) {
        setSavedMsg(true);
        setTimeout(() => setSavedMsg(false), 3000);
      }
    } catch (err) {
      alert('Failed to save settings');
    }
  };

  const handleUpdateTelegramSettings = async (updatedSettings) => {
    setSettings(updatedSettings);
    await fetch('/api/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updatedSettings)
    });
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      <div>
        <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Platform Settings & Branding</h1>
        <p className="text-xs text-gray-500">Configure company branding, logo, Telegram bot parameters, and report templates.</p>
      </div>

      {savedMsg && (
        <div className="p-3 bg-green-100 border border-green-300 text-green-800 rounded-xl text-xs font-bold text-center">
          ✅ Settings updated successfully!
        </div>
      )}

      {/* Branding Form */}
      <form onSubmit={handleSaveBranding} className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm space-y-5">
        <div className="flex items-center space-x-3 mb-2">
          <div className="p-2.5 bg-blue-50 rounded-xl border border-blue-100">
            <Building className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-gray-900">Company & Brand Customization</h3>
            <p className="text-xs text-gray-500">Appears on headers, mobile app, and exported PDF reports.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-gray-700 uppercase mb-1">Company / Organization Name</label>
            <input
              type="text"
              value={settings.companyName}
              onChange={(e) => setSettings({ ...settings, companyName: e.target.value })}
              className="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-300 rounded-xl text-sm font-semibold focus:ring-2 focus:ring-blue-500 focus:bg-white focus:outline-none"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-gray-700 uppercase mb-1">Company Logo URL</label>
            <input
              type="text"
              value={settings.logoUrl}
              onChange={(e) => setSettings({ ...settings, logoUrl: e.target.value })}
              className="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-300 rounded-xl text-sm font-mono focus:ring-2 focus:ring-blue-500 focus:bg-white focus:outline-none"
            />
          </div>
        </div>

        {/* Logo Preview */}
        {settings.logoUrl && (
          <div className="p-4 bg-gray-50 rounded-xl border border-gray-200 flex items-center space-x-4">
            <span className="text-xs font-semibold text-gray-500">Logo Preview:</span>
            <img src={settings.logoUrl} alt="Logo Preview" className="h-10 w-auto object-contain" />
          </div>
        )}

        <div>
          <label className="block text-xs font-semibold text-gray-700 uppercase mb-1 flex items-center gap-1">
            <FileText className="w-3.5 h-3.5 text-blue-600" /> PDF Report Footer Line
          </label>
          <input
            type="text"
            value={settings.reportFooterText}
            onChange={(e) => setSettings({ ...settings, reportFooterText: e.target.value })}
            className="w-full px-3.5 py-2.5 bg-gray-50 border border-gray-300 rounded-xl text-xs focus:ring-2 focus:ring-blue-500 focus:bg-white focus:outline-none"
          />
        </div>

        <button
          type="submit"
          className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-xl shadow-sm transition-colors"
        >
          <Save className="w-4 h-4 mr-1.5 inline" /> Save Branding Settings
        </button>
      </form>

      {/* Telegram Configuration Component */}
      <TelegramConfig settings={settings} onUpdate={handleUpdateTelegramSettings} />
    </div>
  );
}
