import { jsPDF } from 'jspdf';

/**
 * Generates an executive PDF report for a DigiCheck Inspection
 */
export function generateInspectionPDF(submission, settings = {}) {
  const doc = new jsPDF();
  const companyName = settings.companyName || 'TechHarmonix';
  const logoUrl = settings.logoUrl || 'https://www.techharmonix.com/_next/image?url=%2Fimages%2Flogo%2FLogo.png&w=256&q=75';

  // Primary Header Bar
  doc.setFillColor(30, 58, 138); // #1e3a8a
  doc.rect(0, 0, 210, 28, 'F');

  // Title Text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`${companyName.toUpperCase()} - DIGICHECK AUDIT REPORT`, 14, 18);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Official Inspection Summary & Compliance Audit`, 14, 24);

  // Score Badge
  const score = submission.score || 0;
  let scoreColor = [34, 197, 94]; // green
  if (score < 75) scoreColor = [239, 68, 68]; // red
  else if (score < 90) scoreColor = [234, 179, 8]; // yellow

  doc.setFillColor(...scoreColor);
  doc.roundedRect(150, 8, 46, 14, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`SCORE: ${score.toFixed(1)}%`, 154, 17);

  // Metadata Box
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`INSPECTION METADATA`, 14, 38);

  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 40, 196, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Template: ${submission.templateTitle}`, 14, 46);
  doc.text(`Inspector: ${submission.inspectorName}`, 14, 52);
  doc.text(`Location: ${submission.location || 'HQ Office'}`, 14, 58);
  doc.text(`Date & Time: ${new Date(submission.submittedAt).toLocaleString()}`, 110, 46);
  doc.text(`Total Items: ${submission.totalItems}`, 110, 52);
  doc.text(`Passed / Failed: ${submission.passedItems} Passed / ${submission.failedItems} Failed`, 110, 58);

  // Checklist Details Table
  let startY = 70;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(`AUDIT ITEM RESULTS`, 14, startY);
  doc.line(14, startY + 2, 196, startY + 2);

  startY += 8;

  // Table Headers
  doc.setFillColor(241, 245, 249);
  doc.rect(14, startY, 182, 8, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('CHECKITEM / QUESTION', 16, startY + 5.5);
  doc.text('STATUS', 140, startY + 5.5);
  doc.text('NOTES / REMARKS', 165, startY + 5.5);

  startY += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  if (submission.answers) {
    Object.entries(submission.answers).forEach(([key, ans]) => {
      if (startY > 270) {
        doc.addPage();
        startY = 20;
      }

      const isPass = ans.status === 'pass';
      const isFail = ans.status === 'fail';

      doc.setTextColor(30, 41, 59);
      const labelText = doc.splitTextToSize(ans.label || key, 120);
      doc.text(labelText, 16, startY);

      if (isPass) {
        doc.setTextColor(22, 163, 74);
        doc.text('PASS', 140, startY);
      } else if (isFail) {
        doc.setTextColor(220, 38, 38);
        doc.text('FAIL ❌', 140, startY);
      } else {
        doc.setTextColor(100, 116, 139);
        doc.text('N/A', 140, startY);
      }

      doc.setTextColor(71, 85, 105);
      const notesText = doc.splitTextToSize(ans.notes || '-', 30);
      doc.text(notesText, 165, startY);

      const itemLines = Math.max(labelText.length, notesText.length);
      startY += itemLines * 5 + 3;

      doc.setDrawColor(241, 245, 249);
      doc.line(14, startY - 2, 196, startY - 2);
    });
  }

  // Signature Block if exists
  if (submission.signature && startY < 240) {
    startY += 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text('DIGITAL SIGNATURE:', 14, startY);

    try {
      doc.addImage(submission.signature, 'PNG', 14, startY + 3, 50, 20);
    } catch (e) {
      doc.text('[Digital Signature Verified]', 14, startY + 10);
    }
  }

  // Footer
  const footerText = settings.reportFooterText || `Confidential Report - Generated by ${companyName} DigiCheck Platform`;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(footerText, 105, 290, { align: 'center' });

  // Download trigger
  const fileName = `DigiCheck_Report_${submission.id}_${submission.inspectorName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
  doc.save(fileName);
}
